noinst_LIBRARIES = libCCTM.a

# root
CCTM = $(srcdir)/CCTM/src

libCCTM_a_SOURCES = 

# aero
AERO = $(srcdir)/$(CCTM)/aero/aero6
libAERO = $(AERO)/libCCTM_a-
libCCTM_a_SOURCES += \
	$(AERO)/AEROMET_DATA.F 

# includes
ICL = $(srcdir)/$(CCTM)/ICL/fixed
libCCTM_a_SOURCES += \
	$(ICL)/const/CONST.EXT
# ICL/fixed/emctrl/EMISPRM.EXT \
# ICL/fixed/filenames/FILES_CTM.EXT \
# ICL/fixed/mpi/PE_COMM.EXT
#
# MPI
# # par/mpi/mpcomm_init.F
# #
# #
# libCCTM_a_CPPFLAGS  = -DSUBST_FILES_ID=\"FILES_CTM.EXT\"
libCCTM_a_CPPFLAGS  =
libCCTM_a_CPPFLAGS += -DSUBST_CONST=\"CONST.EXT\"
# libCCTM_a_CPPFLAGS += -DSUBST_EMISPRM=\"EMISPRM.EXT\"
# libCCTM_a_CPPFLAGS += -Dparallel -Dmpas
#
libCCTM_a_FFLAGS = $(CCTM_FFLAGS)
libCCTM_a_FFLAGS += -I . \
	-I $(ICL)/filenames -I $(ICL)/const -I $(ICL)/emctrl \
	-I $(builddir)/../../util \
	-I $(builddir)/../../shr

libCCTM_a_FCFLAGS  = $(CCTM_FCFLAGS)
libCCTM_a_FCFLAGS += -I $(builddir)/../../util

.PHONY : clean-modules

clean-modules:
	-test -z "$(FC_MODEXT)" || rm -f *.$(FC_MODEXT)

clean-local: clean-modules

$(libAERO)AEROMET_DATA.$(OBJEXT) : $(ICL)/const/CONST.EXT
