module aqm_tracers_mod

  use aqm_rc_mod,     only : AQM_RC_SUCCESS
  use aqm_config_mod, only : aqm_config_type

  implicit none

! logical :: readrestart = .false.
! integer :: kemit

  !-----------------------------------------------------------------------  
  ! tracer info
  !-----------------------------------------------------------------------
  ! Tracer index:
  ! default initialization for all sulfur and carbon species is 0 (undefined)
  !     1. DMS       = Dimethyl sulfide            = CH3SCH3  
  !     2. SO2       = Sulfur dioxide              = SO2               
  !     3. SO4       = Sulfate                     = SO4            
  !     4. MSA       = Methane sulfonic acid       = CH3SO3H             
  INTEGER            :: NDMS=1, NSO2=2, NSO4=3, NMSA=4
  
  ! -- predefined atmospheric tracers
  INTEGER            ::     P_atm_ptem = 0  ! not connected
  INTEGER            ::     P_atm_shum = 1
  INTEGER            ::     P_atm_cldq = 2
  INTEGER            ::     P_atm_o3mr = 3

  INTEGER            ::     P_qc = 1
  INTEGER            ::     P_qi = 1
  INTEGER            ::     P_qv = 1
  INTEGER            ::     P_qr = 1

  INTEGER            ::     P_bc2 = 1
  INTEGER            ::     P_tr2 = 1
  INTEGER            ::     P_ho = 1
  INTEGER            ::     P_h2o2 = 1
  INTEGER            ::     P_no3 = 1
  INTEGER            ::     P_so2 = 1
  INTEGER            ::     P_sulf = 1
  INTEGER            ::     P_msa = 1
  INTEGER            ::     P_dms = 1
  INTEGER            ::     P_bc1 = 1
  INTEGER            ::     P_oc1 = 1
  INTEGER            ::     P_oc2 = 1
  INTEGER            ::     P_p25 = 1
  INTEGER            ::     P_p10 = 1
  INTEGER            ::     P_o3 = 1
  INTEGER            ::     P_ch4 = 1
  INTEGER            ::     P_co = 1
  INTEGER            ::     P_co2 = 1
  INTEGER            ::     P_ete = 1
  INTEGER            ::     P_udd = 1
  INTEGER            ::     P_hket = 1
  INTEGER            ::     P_api = 1
  INTEGER            ::     P_lim = 1
  INTEGER            ::     P_dien = 1
  INTEGER            ::     P_macr = 1
  INTEGER            ::     P_ch3o2 = 1
  INTEGER            ::     P_ethp = 1
  INTEGER            ::     P_hcl = 1
  INTEGER            ::     P_ald2 = 1
  INTEGER            ::     P_alk1 = 1
  INTEGER            ::     P_api1 = 1
  INTEGER            ::     P_api2 = 1
  INTEGER            ::     P_aro1 = 1
  INTEGER            ::     P_aro2 = 1
  INTEGER            ::     P_c2h4 = 1
  INTEGER            ::     P_c2h6 = 1
  INTEGER            ::     P_c3h6 = 1
  INTEGER            ::     P_c3h8 = 1
  INTEGER            ::     P_eo = 1
  INTEGER            ::     P_eto2 = 1
  INTEGER            ::     P_h2 = 1
  INTEGER            ::     P_isooh = 1
  INTEGER            ::     P_lim1 = 1
  INTEGER            ::     P_lim2 = 1
  INTEGER            ::     P_mek = 1
  INTEGER            ::     P_mvkooh = 1
  INTEGER            ::     P_n2o = 1
  INTEGER            ::     P_o = 1
  INTEGER            ::     P_o1d_cb4 = 1
  INTEGER            ::     P_ole1 = 1
  INTEGER            ::     P_po2 = 1
  INTEGER            ::     P_pro2 = 1
  INTEGER            ::     P_xooh = 1


  INTEGER            ::     P_ano2 = 1
  INTEGER            ::     P_c2h5oh = 1
  INTEGER            ::     P_c2o3 = 1
  INTEGER            ::     P_ch3oh = 1
  INTEGER            ::     P_ch3sch2oo = 1
  INTEGER            ::     P_ch3so2 = 1
  INTEGER            ::     P_ch3so2ch2oo = 1
  INTEGER            ::     P_ch3so2h = 1
  INTEGER            ::     P_ch3so2oo = 1
  INTEGER            ::     P_ch3so3 = 1
  INTEGER            ::     P_cro = 1
  INTEGER            ::     P_dmso = 1
  INTEGER            ::     P_dmso2 = 1
  INTEGER            ::     P_isopn = 1
  INTEGER            ::     P_isopo2 = 1
  INTEGER            ::     P_isopp = 1
  INTEGER            ::     P_isoprd = 1
  INTEGER            ::     P_mtf = 1
  INTEGER            ::     P_nap = 1
  INTEGER            ::     P_op3 = 1
  INTEGER            ::     P_open = 1
  INTEGER            ::     P_ro2 = 1
  INTEGER            ::     P_soag = 1
  INTEGER            ::     P_to2 = 1
  INTEGER            ::     P_xo2 = 1
  INTEGER            ::     P_xpar = 1

  INTEGER            ::     P_aceto2 = 1
  INTEGER            ::     P_alko2 = 1
  INTEGER            ::     P_benzene = 1
  INTEGER            ::     P_benzo2 = 1
  INTEGER            ::     P_benzooh = 1
  INTEGER            ::     P_bepomuc = 1
  INTEGER            ::     P_bigald1 = 1
  INTEGER            ::     P_bigald2 = 1
  INTEGER            ::     P_bigald3 = 1
  INTEGER            ::     P_bigald4 = 1
  INTEGER            ::     P_bigalk = 1
  INTEGER            ::     P_bigene = 1
  INTEGER            ::     P_c10h16 = 1
  INTEGER            ::     P_c6h5o2 = 1
  INTEGER            ::     P_c6h5ooh = 1
  INTEGER            ::     P_eneo2 = 1
  INTEGER            ::     P_iso2 = 1
  INTEGER            ::     P_isopr = 1
  INTEGER            ::     P_malo2 = 1
  INTEGER            ::     P_meko2 = 1
  INTEGER            ::     P_mvko2 = 1
  INTEGER            ::     P_pbznit = 1
  INTEGER            ::     P_phen = 1
  INTEGER            ::     P_pheno = 1
  INTEGER            ::     P_pheno2 = 1
  INTEGER            ::     P_phenooh = 1
  INTEGER            ::     P_terpo2 = 1
  INTEGER            ::     P_xoh = 1

  INTEGER            ::     P_acbzo2 = 1
  INTEGER            ::     P_bald = 1
  INTEGER            ::     P_bzoo = 1
  INTEGER            ::     P_bzooh = 1
  INTEGER            ::     P_c5h8 = 1
  INTEGER            ::     P_ch3co2h = 1
  INTEGER            ::     P_clno2 = 1
  INTEGER            ::     P_dicarbo2 = 1
  INTEGER            ::     P_hso3 = 1
  INTEGER            ::     P_mdialo2 = 1
  INTEGER            ::     P_nc4h10 = 1
  INTEGER            ::     P_npropol = 1
  INTEGER            ::     P_oxyl = 1
  INTEGER            ::     P_smpa = 1
  INTEGER            ::     P_smpbb = 1
  INTEGER            ::     P_so3 = 1
  INTEGER            ::     P_tepomuc = 1
  INTEGER            ::     P_toluene = 1
  INTEGER            ::     P_voca = 1
  INTEGER            ::     P_vocbb = 1
  INTEGER            ::     P_xyleno2 = 1
  INTEGER            ::     P_xylenooh = 1
  INTEGER            ::     P_xylol = 1
  INTEGER            ::     P_xylolo2 = 1
  INTEGER            ::     P_xylolooh = 1

  INTEGER            ::     P_anhy = 1
  INTEGER            ::     P_apinene = 1
  INTEGER            ::     P_arnoh14 = 1
  INTEGER            ::     P_arnoh17 = 1
  INTEGER            ::     P_aroh14 = 1
  INTEGER            ::     P_aroh17 = 1
  INTEGER            ::     P_bpinene = 1
  INTEGER            ::     P_c2h2 = 1
  INTEGER            ::     P_cdicleth = 1
  INTEGER            ::     P_ch2cl2 = 1
  INTEGER            ::     P_ch3ccl3 = 1
  INTEGER            ::     P_ch3cl = 1
  INTEGER            ::     P_chcl3 = 1
  INTEGER            ::     P_dime35eb = 1
  INTEGER            ::     P_ipropol = 1
  INTEGER            ::     P_methtol = 1
  INTEGER            ::     P_noa = 1
  INTEGER            ::     P_oethtol = 1
  INTEGER            ::     P_pethtol = 1
  INTEGER            ::     P_raroh14 = 1
  INTEGER            ::     P_raroh17 = 1
  INTEGER            ::     P_tbut2ene = 1
  INTEGER            ::     P_tce = 1
  INTEGER            ::     P_tdicleth = 1
  INTEGER            ::     P_tm123b = 1
  INTEGER            ::     P_tm124b = 1
  INTEGER            ::     P_tm135b = 1
  INTEGER            ::     P_tricleth = 1

  INTEGER            ::     P_c2h5o2 = 1
  INTEGER            ::     P_ch3oo = 1
  INTEGER            ::     P_ch3s = 1
  INTEGER            ::     P_ch3so = 1
  INTEGER            ::     P_hoch2ch2o2 = 1
  INTEGER            ::     P_ic3h7o2 = 1
  INTEGER            ::     P_msia = 1
  INTEGER            ::     P_nrn12o2 = 1
  INTEGER            ::     P_nrn6o2 = 1
  INTEGER            ::     P_nrn9o2 = 1
  INTEGER            ::     P_rn10o2 = 1
  INTEGER            ::     P_rn11o2 = 1
  INTEGER            ::     P_rn12o2 = 1
  INTEGER            ::     P_rn13ao2 = 1
  INTEGER            ::     P_rn13o2 = 1
  INTEGER            ::     P_rn14o2 = 1
  INTEGER            ::     P_rn15ao2 = 1
  INTEGER            ::     P_rn15o2 = 1
  INTEGER            ::     P_rn16ao2 = 1
  INTEGER            ::     P_rn16o2 = 1
  INTEGER            ::     P_rn17o2 = 1
  INTEGER            ::     P_rn18ao2 = 1
  INTEGER            ::     P_rn18o2 = 1
  INTEGER            ::     P_rn19o2 = 1
  INTEGER            ::     P_rn8o2 = 1
  INTEGER            ::     P_rn9o2 = 1
  INTEGER            ::     P_ru10o2 = 1
  INTEGER            ::     P_ru12o2 = 1
  INTEGER            ::     P_ru14o2 = 1

  INTEGER            ::     P_ch3o2no2 = 1
  INTEGER            ::     P_etoh = 1
  INTEGER            ::     P_form = 1
  INTEGER            ::     P_ispd = 1
  INTEGER            ::     P_meo2 = 1
  INTEGER            ::     P_meoh = 1
  INTEGER            ::     P_nrtn28o2 = 1
  INTEGER            ::     P_nrtx28o2 = 1
  INTEGER            ::     P_nru12o2 = 1
  INTEGER            ::     P_nru14o2 = 1
  INTEGER            ::     P_ra13o2 = 1
  INTEGER            ::     P_ra16o2 = 1
  INTEGER            ::     P_ra19ao2 = 1
  INTEGER            ::     P_ra19co2 = 1
  INTEGER            ::     P_ra22ao2 = 1
  INTEGER            ::     P_ra22bo2 = 1
  INTEGER            ::     P_ra25o2 = 1
  INTEGER            ::     P_rtn10o2 = 1
  INTEGER            ::     P_rtn14o2 = 1
  INTEGER            ::     P_rtn23o2 = 1
  INTEGER            ::     P_rtn24o2 = 1
  INTEGER            ::     P_rtn25o2 = 1
  INTEGER            ::     P_rtn26o2 = 1
  INTEGER            ::     P_rtn28o2 = 1
  INTEGER            ::     P_rtx22o2 = 1
  INTEGER            ::     P_rtx24o2 = 1
  INTEGER            ::     P_rtx28o2 = 1
  INTEGER            ::     P_xo2n = 1
  INTEGER            ::     P_apin = 1
  INTEGER            ::     P_apinaer1 = 1
  INTEGER            ::     P_apinaer2 = 1
  INTEGER            ::     P_apinaer3 = 1
  INTEGER            ::     P_apinaer4 = 1
  INTEGER            ::     P_bpin = 1
  INTEGER            ::     P_bpinaer1 = 1
  INTEGER            ::     P_bpinaer2 = 1
  INTEGER            ::     P_bpinaer3 = 1
  INTEGER            ::     P_bpinaer4 = 1
  INTEGER            ::     P_bpinaer5 = 1
  INTEGER            ::     P_cres = 1
  INTEGER            ::     P_cslaer = 1
  INTEGER            ::     P_hum = 1
  INTEGER            ::     P_humaer = 1
  INTEGER            ::     P_isop = 1
  INTEGER            ::     P_limaer1 = 1
  INTEGER            ::     P_limaer2 = 1
  INTEGER            ::     P_o1d = 1
  INTEGER            ::     P_oci = 1
  INTEGER            ::     P_ociaer1 = 1
  INTEGER            ::     P_ociaer2 = 1
  INTEGER            ::     P_ter = 1
  INTEGER            ::     P_teraer1 = 1
  INTEGER            ::     P_teraer2 = 1
  INTEGER            ::     P_terp = 1
  INTEGER            ::     P_terpaer = 1
  INTEGER            ::     P_tolaer1 = 1
  INTEGER            ::     P_tolaer2 = 1

  INTEGER            ::     P_acet = 1
  INTEGER            ::     P_alkh = 1
  INTEGER            ::     P_alkhaer1 = 1
  INTEGER            ::     P_c3h6ooh = 1
  INTEGER            ::     P_ch3cooh = 1
  INTEGER            ::     P_ch3ooh = 1
  INTEGER            ::     P_cl = 1
  INTEGER            ::     P_cl2 = 1
  INTEGER            ::     P_clo = 1
  INTEGER            ::     P_fmcl = 1
  INTEGER            ::     P_hco3 = 1
  INTEGER            ::     P_hg0 = 1
  INTEGER            ::     P_hg2 = 1
  INTEGER            ::     P_hocl = 1
  INTEGER            ::     P_isoaer1 = 1
  INTEGER            ::     P_isoaer2 = 1
  INTEGER            ::     P_pah = 1
  INTEGER            ::     P_pahaer1 = 1
  INTEGER            ::     P_pahaer2 = 1
  INTEGER            ::     P_panx = 1
  INTEGER            ::     P_par = 1
  INTEGER            ::     P_ror = 1
  INTEGER            ::     P_sulaer = 1
  INTEGER            ::     P_xylaer1 = 1
  INTEGER            ::     P_xylaer2 = 1

  INTEGER            ::     P_acetol = 1
  INTEGER            ::     P_acetp = 1
  INTEGER            ::     P_alkooh = 1
  INTEGER            ::     P_c2h5co3h = 1
  INTEGER            ::     P_c2h5ooh = 1
  INTEGER            ::     P_cvasoax = 1
  INTEGER            ::     P_cvbsoax = 1
  INTEGER            ::     P_etooh = 1
  INTEGER            ::     P_glyald = 1
  INTEGER            ::     P_hcooh = 1
  INTEGER            ::     P_hoc2h4ooh = 1
  INTEGER            ::     P_hoch2co3h = 1
  INTEGER            ::     P_hydrald = 1
  INTEGER            ::     P_mekooh = 1
  INTEGER            ::     P_onitr = 1
  INTEGER            ::     P_phan = 1
  INTEGER            ::     P_ppn = 1
  INTEGER            ::     P_prooh = 1
  INTEGER            ::     P_rn10ooh = 1
  INTEGER            ::     P_rn13ooh = 1
  INTEGER            ::     P_rn16ooh = 1
  INTEGER            ::     P_rn19ooh = 1
  INTEGER            ::     P_rtn26pan = 1
  INTEGER            ::     P_ru12pan = 1
  INTEGER            ::     P_terpooh = 1
  INTEGER            ::     P_tolooh = 1

  INTEGER            ::     P_nrn12ooh = 1
  INTEGER            ::     P_nrn6ooh = 1
  INTEGER            ::     P_nrn9ooh = 1
  INTEGER            ::     P_nrtn28ooh = 1
  INTEGER            ::     P_nru12ooh = 1
  INTEGER            ::     P_nru14ooh = 1
  INTEGER            ::     P_ra13ooh = 1
  INTEGER            ::     P_ra16ooh = 1
  INTEGER            ::     P_ra19ooh = 1
  INTEGER            ::     P_rn11ooh = 1
  INTEGER            ::     P_rn12ooh = 1
  INTEGER            ::     P_rn14ooh = 1
  INTEGER            ::     P_rn15ooh = 1
  INTEGER            ::     P_rn17ooh = 1
  INTEGER            ::     P_rn18ooh = 1
  INTEGER            ::     P_rn8ooh = 1
  INTEGER            ::     P_rn9ooh = 1
  INTEGER            ::     P_rtn14ooh = 1
  INTEGER            ::     P_rtn23ooh = 1
  INTEGER            ::     P_rtn24ooh = 1
  INTEGER            ::     P_rtn25ooh = 1
  INTEGER            ::     P_rtn26ooh = 1
  INTEGER            ::     P_rtn28ooh = 1
  INTEGER            ::     P_ru10ooh = 1
  INTEGER            ::     P_ru12ooh = 1
  INTEGER            ::     P_ru14ooh = 1


  INTEGER            ::     P_c2h5no3 = 1
  INTEGER            ::     P_ch3no3 = 1
  INTEGER            ::     P_hoc2h4no3 = 1
  INTEGER            ::     P_nrtx28ooh = 1
  INTEGER            ::     P_ra13no3 = 1
  INTEGER            ::     P_ra16no3 = 1
  INTEGER            ::     P_ra19no3 = 1
  INTEGER            ::     P_ra22ooh = 1
  INTEGER            ::     P_ra25ooh = 1
  INTEGER            ::     P_rcooh25 = 1
  INTEGER            ::     P_rn10no3 = 1
  INTEGER            ::     P_rn12no3 = 1
  INTEGER            ::     P_rn13no3 = 1
  INTEGER            ::     P_rn15no3 = 1
  INTEGER            ::     P_rn16no3 = 1
  INTEGER            ::     P_rn18no3 = 1
  INTEGER            ::     P_rn19no3 = 1
  INTEGER            ::     P_rn9no3 = 1
  INTEGER            ::     P_rtn10ooh = 1
  INTEGER            ::     P_rtn25no3 = 1
  INTEGER            ::     P_rtn28no3 = 1
  INTEGER            ::     P_rtx22ooh = 1
  INTEGER            ::     P_rtx24ooh = 1
  INTEGER            ::     P_rtx28no3 = 1
  INTEGER            ::     P_rtx28ooh = 1
  INTEGER            ::     P_ru14no3 = 1

  INTEGER            ::     P_c2h5cho = 1
  INTEGER            ::     P_carb10 = 1
  INTEGER            ::     P_carb12 = 1
  INTEGER            ::     P_carb13 = 1
  INTEGER            ::     P_carb14 = 1
  INTEGER            ::     P_carb15 = 1
  INTEGER            ::     P_carb16 = 1
  INTEGER            ::     P_carb17 = 1
  INTEGER            ::     P_carb3 = 1
  INTEGER            ::     P_carb6 = 1
  INTEGER            ::     P_carb7 = 1
  INTEGER            ::     P_carb9 = 1
  INTEGER            ::     P_ccarb12 = 1
  INTEGER            ::     P_ch3cho = 1
  INTEGER            ::     P_hoch2cho = 1
  INTEGER            ::     P_ic3h7no3 = 1
  INTEGER            ::     P_nucarb12 = 1
  INTEGER            ::     P_ra22no3 = 1
  INTEGER            ::     P_ra25no3 = 1
  INTEGER            ::     P_rtn23no3 = 1
  INTEGER            ::     P_rtx22no3 = 1
  INTEGER            ::     P_rtx24no3 = 1
  INTEGER            ::     P_ucarb10 = 1
  INTEGER            ::     P_ucarb12 = 1
  INTEGER            ::     P_udcarb11 = 1
  INTEGER            ::     P_udcarb8 = 1

  INTEGER            ::     P_alk3 = 1
  INTEGER            ::     P_bacl = 1
  INTEGER            ::     P_carb11a = 1
  INTEGER            ::     P_ccho = 1
  INTEGER            ::     P_cco_oh = 1
  INTEGER            ::     P_dcb1 = 1
  INTEGER            ::     P_dcb2 = 1
  INTEGER            ::     P_dcb3 = 1
  INTEGER            ::     P_ethene = 1
  INTEGER            ::     P_h2so4 = 1
  INTEGER            ::     P_isoprene = 1
  INTEGER            ::     P_isoprod = 1
  INTEGER            ::     P_methacro = 1
  INTEGER            ::     P_ol2 = 1
  INTEGER            ::     P_prod2 = 1
  INTEGER            ::     P_rcho = 1
  INTEGER            ::     P_rco_oh = 1
  INTEGER            ::     P_tncarb10 = 1
  INTEGER            ::     P_tncarb11 = 1
  INTEGER            ::     P_tncarb12 = 1
  INTEGER            ::     P_tncarb15 = 1
  INTEGER            ::     P_tncarb26 = 1
  INTEGER            ::     P_txcarb22 = 1
  INTEGER            ::     P_txcarb24 = 1
  INTEGER            ::     P_udcarb14 = 1
  INTEGER            ::     P_udcarb17 = 1

  INTEGER            ::     P_alk4 = 1
  INTEGER            ::     P_alk5 = 1
  INTEGER            ::     P_bzco_o2 = 1
  INTEGER            ::     P_cco_o2 = 1
  INTEGER            ::     P_cco_ooh = 1
  INTEGER            ::     P_c_o2 = 1
  INTEGER            ::     P_cooh = 1
  INTEGER            ::     P_ma_pan = 1
  INTEGER            ::     P_ma_rco3 = 1
  INTEGER            ::     P_nphe = 1
  INTEGER            ::     P_ole2 = 1
  INTEGER            ::     P_pan2 = 1
  INTEGER            ::     P_pbzn = 1
  INTEGER            ::     P_pcg1_b_c = 1
  INTEGER            ::     P_pcg2_b_c = 1
  INTEGER            ::     P_pcg3_b_c = 1
  INTEGER            ::     P_pcg4_b_c = 1
  INTEGER            ::     P_r2o2 = 1
  INTEGER            ::     P_rco_o2 = 1
  INTEGER            ::     P_rco_ooh = 1
  INTEGER            ::     P_rno3 = 1
  INTEGER            ::     P_ro2_n = 1
  INTEGER            ::     P_ro2_r = 1
  INTEGER            ::     P_rooh = 1
  INTEGER            ::     P_xc = 1
  INTEGER            ::     P_xn = 1

  INTEGER            ::     P_opcg1_b_c = 1
  INTEGER            ::     P_opcg1_b_o = 1
  INTEGER            ::     P_opcg2_b_c = 1
  INTEGER            ::     P_opcg2_b_o = 1
  INTEGER            ::     P_opcg3_b_c = 1
  INTEGER            ::     P_opcg3_b_o = 1
  INTEGER            ::     P_opcg4_b_c = 1
  INTEGER            ::     P_opcg4_b_o = 1
  INTEGER            ::     P_opcg5_b_c = 1
  INTEGER            ::     P_opcg6_b_c = 1
  INTEGER            ::     P_opcg7_b_c = 1
  INTEGER            ::     P_opcg8_b_c = 1
  INTEGER            ::     P_pcg1_b_o = 1
  INTEGER            ::     P_pcg2_b_o = 1
  INTEGER            ::     P_pcg3_b_o = 1
  INTEGER            ::     P_pcg4_b_o = 1
  INTEGER            ::     P_pcg5_b_c = 1
  INTEGER            ::     P_pcg5_b_o = 1
  INTEGER            ::     P_pcg6_b_c = 1
  INTEGER            ::     P_pcg6_b_o = 1
  INTEGER            ::     P_pcg7_b_c = 1
  INTEGER            ::     P_pcg7_b_o = 1
  INTEGER            ::     P_pcg8_b_c = 1
  INTEGER            ::     P_pcg8_b_o = 1
  INTEGER            ::     P_pcg9_b_c = 1
  INTEGER            ::     P_pcg9_b_o = 1

  INTEGER            ::     P_opcg1_f_c = 1
  INTEGER            ::     P_opcg2_f_c = 1
  INTEGER            ::     P_opcg3_f_c = 1
  INTEGER            ::     P_opcg4_f_c = 1
  INTEGER            ::     P_opcg5_b_o = 1
  INTEGER            ::     P_opcg5_f_c = 1
  INTEGER            ::     P_opcg6_b_o = 1
  INTEGER            ::     P_opcg6_f_c = 1
  INTEGER            ::     P_opcg7_b_o = 1
  INTEGER            ::     P_opcg7_f_c = 1
  INTEGER            ::     P_opcg8_b_o = 1
  INTEGER            ::     P_opcg8_f_c = 1
  INTEGER            ::     P_pcg1_f_c = 1
  INTEGER            ::     P_pcg1_f_o = 1
  INTEGER            ::     P_pcg2_f_c = 1
  INTEGER            ::     P_pcg2_f_o = 1
  INTEGER            ::     P_pcg3_f_c = 1
  INTEGER            ::     P_pcg3_f_o = 1
  INTEGER            ::     P_pcg4_f_c = 1
  INTEGER            ::     P_pcg4_f_o = 1
  INTEGER            ::     P_pcg5_f_c = 1
  INTEGER            ::     P_pcg5_f_o = 1
  INTEGER            ::     P_pcg6_f_c = 1
  INTEGER            ::     P_pcg7_f_c = 1
  INTEGER            ::     P_pcg8_f_c = 1
  INTEGER            ::     P_pcg9_f_c = 1

  INTEGER            ::     P_ant1_c = 1
  INTEGER            ::     P_ant1_o = 1
  INTEGER            ::     P_ant2_c = 1
  INTEGER            ::     P_ant2_o = 1
  INTEGER            ::     P_ant3_c = 1
  INTEGER            ::     P_ant3_o = 1
  INTEGER            ::     P_ant4_c = 1
  INTEGER            ::     P_ant4_o = 1
  INTEGER            ::     P_biog1_c = 1
  INTEGER            ::     P_biog1_o = 1
  INTEGER            ::     P_biog2_c = 1
  INTEGER            ::     P_biog2_o = 1
  INTEGER            ::     P_biog3_c = 1
  INTEGER            ::     P_biog4_c = 1
  INTEGER            ::     P_opcg1_f_o = 1
  INTEGER            ::     P_opcg2_f_o = 1
  INTEGER            ::     P_opcg3_f_o = 1
  INTEGER            ::     P_opcg4_f_o = 1
  INTEGER            ::     P_opcg5_f_o = 1
  INTEGER            ::     P_opcg6_f_o = 1
  INTEGER            ::     P_opcg7_f_o = 1
  INTEGER            ::     P_opcg8_f_o = 1
  INTEGER            ::     P_pcg6_f_o = 1
  INTEGER            ::     P_pcg7_f_o = 1
  INTEGER            ::     P_pcg8_f_o = 1
  INTEGER            ::     P_pcg9_f_o = 1

  INTEGER            ::     P_aacd = 1
  INTEGER            ::     P_aldx = 1
  INTEGER            ::     P_biog3_o = 1
  INTEGER            ::     P_biog4_o = 1
  INTEGER            ::     P_cxo3 = 1
  INTEGER            ::     P_etha = 1
  INTEGER            ::     P_facd = 1
  INTEGER            ::     P_iole = 1
  INTEGER            ::     P_mepx = 1
  INTEGER            ::     P_ntr = 1
  INTEGER            ::     P_ole = 1
  INTEGER            ::     P_pacd = 1
  INTEGER            ::     P_pna = 1



!=======


  INTEGER            ::     P_claj = 1
  INTEGER            ::     P_csl = 1
  INTEGER            ::     P_cvasoa1 = 1
  INTEGER            ::     P_cvasoa2 = 1
  INTEGER            ::     P_cvasoa3 = 1
  INTEGER            ::     P_cvasoa4 = 1
  INTEGER            ::     P_cvbsoa1 = 1
  INTEGER            ::     P_cvbsoa2 = 1
  INTEGER            ::     P_cvbsoa3 = 1
  INTEGER            ::     P_cvbsoa4 = 1
  INTEGER            ::     P_hace = 1
  INTEGER            ::     P_ho2 = 1
  INTEGER            ::     P_ishp = 1
  INTEGER            ::     P_iso = 1
  INTEGER            ::     P_ison = 1
  INTEGER            ::     P_mahp = 1
  INTEGER            ::     P_mbo = 1
  INTEGER            ::     P_mpan = 1
  INTEGER            ::     P_naai = 1
  INTEGER            ::     P_naaj = 1
  INTEGER            ::     P_nald = 1
  INTEGER            ::     P_nh4ai = 1
  INTEGER            ::     P_nh4aj = 1
  INTEGER            ::     P_no3ai = 1
  INTEGER            ::     P_no3aj = 1
  INTEGER            ::     P_onit = 1
  INTEGER            ::     P_sesq = 1
  INTEGER            ::     P_so4ai = 1
  INTEGER            ::     P_so4aj = 1

  INTEGER            ::     P_aco3 = 1
  INTEGER            ::     P_ald = 1
  INTEGER            ::     P_dcb = 1
  INTEGER            ::     P_eth = 1
  INTEGER            ::     P_gly = 1
  INTEGER            ::     P_hc3 = 1
  INTEGER            ::     P_hc5 = 1
  INTEGER            ::     P_hc8 = 1
  INTEGER            ::     P_hcho = 1
  INTEGER            ::     P_hno3 = 1
  INTEGER            ::     P_hno4 = 1
  INTEGER            ::     P_hono = 1
  INTEGER            ::     P_ket = 1
  INTEGER            ::     P_mgly = 1
  INTEGER            ::     P_n2o5 = 1
  INTEGER            ::     P_nh3 = 1
  INTEGER            ::     P_no = 1
  INTEGER            ::     P_no2 = 1
  INTEGER            ::     P_oli = 1
  INTEGER            ::     P_olt = 1
  INTEGER            ::     P_op1 = 1
  INTEGER            ::     P_op2 = 1
  INTEGER            ::     P_ora1 = 1
  INTEGER            ::     P_ora2 = 1
  INTEGER            ::     P_paa = 1
  INTEGER            ::     P_pan = 1
  INTEGER            ::     P_tol = 1
  INTEGER            ::     P_tpan = 1
  INTEGER            ::     P_xyl = 1

  INTEGER            ::     P_ac0 = 1
  INTEGER            ::     P_antha = 1
  INTEGER            ::     P_asoa1i = 1
  INTEGER            ::     P_asoa1j = 1
  INTEGER            ::     P_asoa2i = 1
  INTEGER            ::     P_asoa2j = 1
  INTEGER            ::     P_asoa3i = 1
  INTEGER            ::     P_asoa3j = 1
  INTEGER            ::     P_asoa4i = 1
  INTEGER            ::     P_asoa4j = 1
  INTEGER            ::     P_bsoa1i = 1
  INTEGER            ::     P_bsoa1j = 1
  INTEGER            ::     P_bsoa2i = 1
  INTEGER            ::     P_bsoa2j = 1
  INTEGER            ::     P_bsoa3i = 1
  INTEGER            ::     P_bsoa3j = 1
  INTEGER            ::     P_bsoa4i = 1
  INTEGER            ::     P_bsoa4j = 1
  INTEGER            ::     P_clai = 1
  INTEGER            ::     P_corn = 1
  INTEGER            ::     P_eci = 1
  INTEGER            ::     P_ecj = 1
  INTEGER            ::     P_nu0 = 1
  INTEGER            ::     P_orgpai = 1
  INTEGER            ::     P_orgpaj = 1
  INTEGER            ::     P_p25i = 1
  INTEGER            ::     P_p25j = 1
  INTEGER            ::     P_seas = 1
  INTEGER            ::     P_soila = 1


  INTEGER            ::     P_ac0cw = 1
  INTEGER            ::     P_anthcw = 1
  INTEGER            ::     P_asoa1cwi = 1
  INTEGER            ::     P_asoa1cwj = 1
  INTEGER            ::     P_asoa2cwi = 1
  INTEGER            ::     P_asoa2cwj = 1
  INTEGER            ::     P_asoa3cwi = 1
  INTEGER            ::     P_asoa4cwi = 1
  INTEGER            ::     P_bsoa1cwi = 1
  INTEGER            ::     P_bsoa2cwi = 1
  INTEGER            ::     P_bsoa3cwi = 1
  INTEGER            ::     P_bsoa4cwi = 1
  INTEGER            ::     P_clcwi = 1
  INTEGER            ::     P_clcwj = 1
  INTEGER            ::     P_eccwi = 1
  INTEGER            ::     P_nacwi = 1
  INTEGER            ::     P_nacwj = 1
  INTEGER            ::     P_nh4cwi = 1
  INTEGER            ::     P_nh4cwj = 1
  INTEGER            ::     P_no3cwi = 1
  INTEGER            ::     P_no3cwj = 1
  INTEGER            ::     P_nu0cw = 1
  INTEGER            ::     P_orgpacwi = 1
  INTEGER            ::     P_p25cwi = 1
  INTEGER            ::     P_seascw = 1
  INTEGER            ::     P_so4cwi = 1
  INTEGER            ::     P_so4cwj = 1
  INTEGER            ::     P_soilcw = 1

  INTEGER            ::     P_asoa3cwj = 1
  INTEGER            ::     P_asoa4cwj = 1
  INTEGER            ::     P_bsoa1cwj = 1
  INTEGER            ::     P_bsoa2cwj = 1
  INTEGER            ::     P_bsoa3cwj = 1
  INTEGER            ::     P_bsoa4cwj = 1
  INTEGER            ::     P_corncw = 1
  INTEGER            ::     P_eccwj = 1
  INTEGER            ::     P_orgpacwj = 1
  INTEGER            ::     P_p25cwj = 1


  INTEGER            ::     P_asympar106 = 1
  INTEGER            ::     P_asympar3 = 1
  INTEGER            ::     P_asympar55 = 1

  INTEGER            ::     P_bscof106 = 1
  INTEGER            ::     P_bscof3 = 1
  INTEGER            ::     P_bscof55 = 1

  INTEGER            ::     P_dust_1 = 1
  INTEGER            ::     P_dust_2 = 1
  INTEGER            ::     P_dust_3 = 1
  INTEGER            ::     P_dust_4 = 1
  INTEGER            ::     P_dust_5 = 1

  INTEGER            ::     P_seas_1 = 1
  INTEGER            ::     P_seas_2 = 1
  INTEGER            ::     P_seas_3 = 1
  INTEGER            ::     P_seas_4 = 1
  INTEGER            ::     P_seas_5 = 1

  INTEGER            ::     P_edust1 = 1
  INTEGER            ::     P_edust2 = 1
  INTEGER            ::     P_edust3 = 1
  INTEGER            ::     P_edust4 = 1
  INTEGER            ::     P_edust5 = 1
  INTEGER            ::     P_eseas1 = 1
  INTEGER            ::     P_eseas2 = 1
  INTEGER            ::     P_eseas3 = 1
  INTEGER            ::     P_eseas4 = 1

  INTEGER            ::     P_extcof106 = 1
  INTEGER            ::     P_extcof3 = 1
  INTEGER            ::     P_extcof3_5 = 1
  INTEGER            ::     P_extcof55 = 1
  INTEGER            ::     P_extcof8_12 = 1

  INTEGER            ::     P_e_iso = 1
  INTEGER            ::     P_e_so2 = 1
  INTEGER            ::     P_e_no = 1
  INTEGER            ::     P_e_co = 1
  INTEGER            ::     P_e_co2 = 1
  INTEGER            ::     P_e_eth = 1
  INTEGER            ::     P_e_hc3 = 1
  INTEGER            ::     P_e_hc5 = 1
  INTEGER            ::     P_e_hc8 = 1
  INTEGER            ::     P_e_xyl = 1
  INTEGER            ::     P_e_ol2 = 1
  INTEGER            ::     P_e_olt = 1
  INTEGER            ::     P_e_oli = 1
  INTEGER            ::     P_e_tol = 1
  INTEGER            ::     P_e_csl = 1
  INTEGER            ::     P_e_hcho = 1
  INTEGER            ::     P_e_ald = 1
  INTEGER            ::     P_e_ket = 1
  INTEGER            ::     P_e_ora2 = 1
  INTEGER            ::     P_e_nh3 = 1
  INTEGER            ::     P_e_pm_25 = 1
  INTEGER            ::     P_e_pm_10 = 1
  INTEGER            ::     P_e_pm25i = 1
  INTEGER            ::     P_e_pm25j = 1
  INTEGER            ::     P_e_eci = 1
  INTEGER            ::     P_e_ecj = 1
  INTEGER            ::     P_e_naai = 1
  INTEGER            ::     P_e_naaj = 1
  INTEGER            ::     P_e_orgi = 1
  INTEGER            ::     P_e_orgj = 1
  INTEGER            ::     P_e_so4i = 1
  INTEGER            ::     P_e_so4j = 1
  INTEGER            ::     P_e_no3i = 1
  INTEGER            ::     P_e_no3j = 1
  INTEGER            ::     P_e_nh4i = 1
  INTEGER            ::     P_e_nh4j = 1
  INTEGER            ::     P_e_nai = 1
  INTEGER            ::     P_e_naj = 1
  INTEGER            ::     P_e_cli = 1
  INTEGER            ::     P_e_clj = 1
  INTEGER            ::     P_e_bigalk = 1
  INTEGER            ::     P_e_bigene = 1
  INTEGER            ::     P_e_c2h4 = 1
  INTEGER            ::     P_e_c2h6 = 1
  INTEGER            ::     P_e_c3h6 = 1
  INTEGER            ::     P_e_c3h8 = 1
  INTEGER            ::     P_e_ch2o = 1
  INTEGER            ::     P_e_ch3cho = 1
  INTEGER            ::     P_e_ch3coch3 = 1
  INTEGER            ::     P_e_mek = 1
  INTEGER            ::     P_e_toluene = 1
  INTEGER            ::     P_e_xylene = 1
  INTEGER            ::     P_e_isop = 1
  INTEGER            ::     P_e_c10h16 = 1
  INTEGER            ::     P_e_voca = 1
  INTEGER            ::     P_e_vocbb = 1
  INTEGER            ::     P_e_macr = 1
  INTEGER            ::     P_e_hono = 1
  INTEGER            ::     P_e_c5h8 = 1
  INTEGER            ::     P_e_tm123b = 1
  INTEGER            ::     P_e_tm124b = 1
  INTEGER            ::     P_e_tm135b = 1
  INTEGER            ::     P_e_oethtol = 1
  INTEGER            ::     P_e_methtol = 1
  INTEGER            ::     P_e_pethtol = 1
  INTEGER            ::     P_e_dime35eb = 1
  INTEGER            ::     P_e_c2h5cho = 1
  INTEGER            ::     P_e_benzene = 1
  INTEGER            ::     P_e_nc4h10 = 1
  INTEGER            ::     P_e_oxyl = 1
  INTEGER            ::     P_e_tbut2ene = 1
  INTEGER            ::     P_e_ch3co2h = 1
  INTEGER            ::     P_e_bc_1 = 1
  INTEGER            ::     P_e_ec_1_25 = 1
  INTEGER            ::     P_e_ec_25_10 = 1
  INTEGER            ::     P_e_oc_dom = 1
  INTEGER            ::     P_e_oc_tra = 1
  INTEGER            ::     P_e_oc_25_10 = 1
  INTEGER            ::     P_e_pm25 = 1
  INTEGER            ::     P_e_pm10 = 1
  INTEGER            ::     P_e_oin_25 = 1
  INTEGER            ::     P_e_oin_10 = 1
  INTEGER            ::     P_e_no2 = 1
  INTEGER            ::     P_e_ch3oh = 1
  INTEGER            ::     P_e_c2h5oh = 1
  INTEGER            ::     P_e_so4c = 1
  INTEGER            ::     P_e_no3c = 1
  INTEGER            ::     P_e_nh4c = 1
  INTEGER            ::     P_e_nac = 1
  INTEGER            ::     P_e_clc = 1
  INTEGER            ::     P_e_orgc = 1
  INTEGER            ::     P_e_ecc = 1
  INTEGER            ::     P_e_orgi_a = 1
  INTEGER            ::     P_e_orgj_a = 1
  INTEGER            ::     P_e_orgi_bb = 1
  INTEGER            ::     P_e_orgj_bb = 1
  INTEGER            ::     P_e_co_a = 1
  INTEGER            ::     P_e_co_bb = 1
  INTEGER            ::     P_e_bc = 1
  INTEGER            ::     P_e_oc = 1
  INTEGER            ::     P_e_sulf = 1
  INTEGER            ::     P_e_soag_bigalk = 1
  INTEGER            ::     P_e_soag_bigene = 1
  INTEGER            ::     P_e_soag_isoprene = 1
  INTEGER            ::     P_e_soag_terpene = 1
  INTEGER            ::     P_e_soag_toluene = 1
  INTEGER            ::     P_e_dust_a1 = 1
  INTEGER            ::     P_e_dust_a3 = 1
  INTEGER            ::     P_e_ncl_a1 = 1
  INTEGER            ::     P_e_ncl_a2 = 1
  INTEGER            ::     P_e_ncl_a3 = 1
  INTEGER            ::     P_e_orgj_num = 1
  INTEGER            ::     P_e_ecj_num = 1
  INTEGER            ::     P_e_so4j_num = 1
  INTEGER            ::     P_e_so4i_num = 1
  INTEGER            ::     P_e_num_a3 = 1
  INTEGER            ::     P_e_dms = 1
  INTEGER            ::     P_e_c2h2 = 1
  INTEGER            ::     P_e_alk3 = 1
  INTEGER            ::     P_e_alk4 = 1
  INTEGER            ::     P_e_alk5 = 1
  INTEGER            ::     P_e_ethene = 1
  INTEGER            ::     P_e_ole1 = 1
  INTEGER            ::     P_e_ole2 = 1
  INTEGER            ::     P_e_aro1 = 1
  INTEGER            ::     P_e_aro2 = 1
  INTEGER            ::     P_e_ccho = 1
  INTEGER            ::     P_e_rcho = 1
  INTEGER            ::     P_e_acet = 1
  INTEGER            ::     P_e_isoprene = 1
  INTEGER            ::     P_e_terp = 1
  INTEGER            ::     P_e_sesq = 1
  INTEGER            ::     P_e_phen = 1
  INTEGER            ::     P_e_cres = 1
  INTEGER            ::     P_e_meoh = 1
  INTEGER            ::     P_e_gly = 1
  INTEGER            ::     P_e_mgly = 1
  INTEGER            ::     P_e_bacl = 1
  INTEGER            ::     P_e_isoprod = 1
  INTEGER            ::     P_e_methacro = 1
  INTEGER            ::     P_e_mvk = 1
  INTEGER            ::     P_e_prod2 = 1
  INTEGER            ::     P_e_ch4 = 1
  INTEGER            ::     P_e_bald = 1
  INTEGER            ::     P_e_hcooh = 1
  INTEGER            ::     P_e_cco_oh = 1
  INTEGER            ::     P_e_rco_oh = 1
  INTEGER            ::     P_e_co2tst = 1
  INTEGER            ::     P_e_cotst = 1
  INTEGER            ::     P_e_ch4tst = 1
  INTEGER            ::     P_e_hcl = 1
  INTEGER            ::     P_e_aldx = 1
  INTEGER            ::     P_e_par = 1
  INTEGER            ::     P_e_ole = 1
  INTEGER            ::     P_e_iole = 1
  INTEGER            ::     P_e_form = 1
  INTEGER            ::     P_e_etha = 1
  INTEGER            ::     P_e_etoh = 1
  INTEGER            ::     P_e_ald2 = 1
  INTEGER            ::     P_e_meo2 = 1
  INTEGER            ::     P_e_psulf = 1
  INTEGER            ::     P_e_ccooh = 1
  INTEGER            ::     P_e_iprod = 1
  INTEGER            ::     P_e_hg2 = 1
  INTEGER            ::     P_e_hg0 = 1
  INTEGER            ::     P_e_fmcl = 1
  INTEGER            ::     P_e_hgp = 1
  INTEGER            ::     P_e_apin = 1
  INTEGER            ::     P_e_bpin = 1
  INTEGER            ::     P_e_lim = 1
  INTEGER            ::     P_e_ter = 1
  INTEGER            ::     P_e_oci = 1
  INTEGER            ::     P_e_hum = 1
  INTEGER            ::     P_e_vash1 = 1
  INTEGER            ::     P_e_vash2 = 1
  INTEGER            ::     P_e_vash3 = 1
  INTEGER            ::     P_e_vash4 = 1
  INTEGER            ::     P_e_vash5 = 1
  INTEGER            ::     P_e_vash6 = 1
  INTEGER            ::     P_e_vash7 = 1
  INTEGER            ::     P_e_vash8 = 1
  INTEGER            ::     P_e_vash9 = 1
  INTEGER            ::     P_e_vash10 = 1
  INTEGER            ::     P_e_vso2 = 1
  INTEGER            ::     P_e_tr1 = 1
  INTEGER            ::     P_e_tr2 = 1
  INTEGER            ::     P_e_tr3 = 1
  INTEGER            ::     P_e_tr4 = 1
  INTEGER            ::     P_e_tr5 = 1

  INTEGER            ::     P_ebu_no = 1
  INTEGER            ::     P_ebu_no2 = 1
  INTEGER            ::     P_ebu_co = 1
  INTEGER            ::     P_ebu_co2 = 1
  INTEGER            ::     P_ebu_eth = 1
  INTEGER            ::     P_ebu_hc3 = 1
  INTEGER            ::     P_ebu_hc5 = 1
  INTEGER            ::     P_ebu_hc8 = 1
  INTEGER            ::     P_ebu_ete = 1
  INTEGER            ::     P_ebu_olt = 1
  INTEGER            ::     P_ebu_oli = 1
  INTEGER            ::     P_ebu_pm25 = 1
  INTEGER            ::     P_ebu_pm10 = 1
  INTEGER            ::     P_ebu_dien = 1
  INTEGER            ::     P_ebu_iso = 1
  INTEGER            ::     P_ebu_api = 1
  INTEGER            ::     P_ebu_lim = 1
  INTEGER            ::     P_ebu_tol = 1
  INTEGER            ::     P_ebu_xyl = 1
  INTEGER            ::     P_ebu_csl = 1
  INTEGER            ::     P_ebu_hcho = 1
  INTEGER            ::     P_ebu_ald = 1
  INTEGER            ::     P_ebu_ket = 1
  INTEGER            ::     P_ebu_macr = 1
  INTEGER            ::     P_ebu_ora1 = 1
  INTEGER            ::     P_ebu_ora2 = 1
  INTEGER            ::     P_ebu_nh3 = 1
  INTEGER            ::     P_ebu_so2 = 1
  INTEGER            ::     P_ebu_dms = 1
  INTEGER            ::     P_ebu_oc = 1
  INTEGER            ::     P_ebu_bc = 1
  INTEGER            ::     P_ebu_sulf = 1
  INTEGER            ::     P_ebu_bigalk = 1
  INTEGER            ::     P_ebu_bigene = 1
  INTEGER            ::     P_ebu_c2h4 = 1
  INTEGER            ::     P_ebu_c2h5oh = 1
  INTEGER            ::     P_ebu_c2h6 = 1
  INTEGER            ::     P_ebu_c3h6 = 1
  INTEGER            ::     P_ebu_c3h8 = 1
  INTEGER            ::     P_ebu_ch2o = 1
  INTEGER            ::     P_ebu_ch3cho = 1
  INTEGER            ::     P_ebu_ch3coch3 = 1
  INTEGER            ::     P_ebu_ch3oh = 1
  INTEGER            ::     P_ebu_mek = 1
  INTEGER            ::     P_ebu_toluene = 1
  INTEGER            ::     P_ebu_open = 1
  INTEGER            ::     P_ebu_c10h16 = 1
  INTEGER            ::     P_ebu_mgly = 1
  INTEGER            ::     P_ebu_ch3cooh = 1
  INTEGER            ::     P_ebu_cres = 1
  INTEGER            ::     P_ebu_glyald = 1
  INTEGER            ::     P_ebu_gly = 1
  INTEGER            ::     P_ebu_acetol = 1
  INTEGER            ::     P_ebu_isop = 1
  INTEGER            ::     P_ebu_mvk = 1
  INTEGER            ::     P_ebu_ch4 = 1
  INTEGER            ::     P_ebu_in_no = 1
  INTEGER            ::     P_ebu_in_no2 = 1
  INTEGER            ::     P_ebu_in_co = 1
  INTEGER            ::     P_ebu_in_co2 = 1
  INTEGER            ::     P_ebu_in_eth = 1
  INTEGER            ::     P_ebu_in_hc3 = 1
  INTEGER            ::     P_ebu_in_hc5 = 1
  INTEGER            ::     P_ebu_in_hc8 = 1
  INTEGER            ::     P_ebu_in_ete = 1
  INTEGER            ::     P_ebu_in_olt = 1
  INTEGER            ::     P_ebu_in_oli = 1
  INTEGER            ::     P_ebu_in_pm25 = 1
  INTEGER            ::     P_ebu_in_pm10 = 1
  INTEGER            ::     P_ebu_in_dien = 1
  INTEGER            ::     P_ebu_in_iso = 1
  INTEGER            ::     P_ebu_in_api = 1
  INTEGER            ::     P_ebu_in_lim = 1
  INTEGER            ::     P_ebu_in_tol = 1
  INTEGER            ::     P_ebu_in_xyl = 1
  INTEGER            ::     P_ebu_in_csl = 1
  INTEGER            ::     P_ebu_in_hcho = 1
  INTEGER            ::     P_ebu_in_ald = 1
  INTEGER            ::     P_ebu_in_ket = 1
  INTEGER            ::     P_ebu_in_macr = 1
  INTEGER            ::     P_ebu_in_ora1 = 1
  INTEGER            ::     P_ebu_in_ora2 = 1
  INTEGER            ::     P_ebu_in_nh3 = 1
  INTEGER            ::     P_ebu_in_so2 = 1
  INTEGER            ::     P_ebu_in_dms = 1
  INTEGER            ::     P_ebu_in_oc = 1
  INTEGER            ::     P_ebu_in_bc = 1
  INTEGER            ::     P_ebu_in_sulf = 1
  INTEGER            ::     P_ebu_in_ash = 1
  INTEGER            ::     P_ebu_in_bigalk = 1
  INTEGER            ::     P_ebu_in_bigene = 1
  INTEGER            ::     P_ebu_in_c2h4 = 1
  INTEGER            ::     P_ebu_in_c2h5oh = 1
  INTEGER            ::     P_ebu_in_c2h6 = 1
  INTEGER            ::     P_ebu_in_c3h6 = 1
  INTEGER            ::     P_ebu_in_c3h8 = 1
  INTEGER            ::     P_ebu_in_ch2o = 1
  INTEGER            ::     P_ebu_in_ch3cho = 1
  INTEGER            ::     P_ebu_in_ch3coch3 = 1
  INTEGER            ::     P_ebu_in_ch3oh = 1
  INTEGER            ::     P_ebu_in_mek = 1
  INTEGER            ::     P_ebu_in_toluene = 1
  INTEGER            ::     P_ebu_in_open = 1
  INTEGER            ::     P_ebu_in_c10h16 = 1
  INTEGER            ::     P_ebu_in_mgly = 1
  INTEGER            ::     P_ebu_in_ch3cooh = 1
  INTEGER            ::     P_ebu_in_cres = 1
  INTEGER            ::     P_ebu_in_glyald = 1
  INTEGER            ::     P_ebu_in_gly = 1
  INTEGER            ::     P_ebu_in_acetol = 1
  INTEGER            ::     P_ebu_in_isop = 1
  INTEGER            ::     P_ebu_in_mvk = 1
  INTEGER            ::     P_ebu_in_ch4 = 1

  INTEGER            ::     P_tr1 = 1
  INTEGER            ::     P_tr3 = 1
  INTEGER            ::     P_tr4 = 1
  INTEGER            ::     P_tr5 = 1

  INTEGER            ::     P_vash_1 = 1
  INTEGER            ::     P_vash_2 = 1
  INTEGER            ::     P_vash_3 = 1
  INTEGER            ::     P_vash_4 = 1
  INTEGER            ::     P_vash_5 = 1
  INTEGER            ::     P_vash_6 = 1
  INTEGER            ::     P_vash_7 = 1
  INTEGER            ::     P_vash_8 = 1
  INTEGER            ::     P_vash_9 = 1
  INTEGER            ::     P_vash_10 = 1

  ! -- totol number of aqmical tracers
! integer            :: num_aqm  = 0
! integer            :: num_moist = 0

! real :: depo_fact

  INTEGER, PARAMETER :: aer_ic_default = 1
  INTEGER , PARAMETER :: PARAM_FIRST_SCALAR = 2

  INTEGER, PARAMETER :: cb05_sorg_aq_kpp = 131
  INTEGER, PARAMETER :: cb05_sorg_vbs_aq_kpp = 132

  INTEGER, PARAMETER :: cbm4_kpp = 110
  INTEGER, PARAMETER :: cbmz = 5
  INTEGER, PARAMETER :: cbmz_bb = 6
  INTEGER, PARAMETER :: cbmz_bb_kpp = 120
  INTEGER, PARAMETER :: cbmz_cam_mam3_aq = 503
  INTEGER, PARAMETER :: cbmz_cam_mam3_noaq = 501
  INTEGER, PARAMETER :: cbmz_cam_mam7_aq = 504
  INTEGER, PARAMETER :: cbmz_cam_mam7_noaq = 502
  INTEGER, PARAMETER :: cbmz_mosaic_4bin = 7
  INTEGER, PARAMETER :: cbmz_mosaic_4bin_aq = 9
  INTEGER, PARAMETER :: cbmz_mosaic_8bin = 8
  INTEGER, PARAMETER :: cbmz_mosaic_8bin_aq = 10
  INTEGER, PARAMETER :: cbmz_mosaic_dms_4bin = 31
  INTEGER, PARAMETER :: cbmz_mosaic_dms_4bin_aq = 32
  INTEGER, PARAMETER :: cbmz_mosaic_dms_8bin = 33
  INTEGER, PARAMETER :: cbmz_mosaic_dms_8bin_aq = 34
  INTEGER, PARAMETER :: cbmz_mosaic_kpp = 170

  INTEGER, PARAMETER :: crimech_kpp = 600
  INTEGER, PARAMETER :: cri_mosaic_4bin_aq_kpp = 611
  INTEGER, PARAMETER :: cri_mosaic_8bin_aq_kpp = 601

  INTEGER, PARAMETER :: gocartracm_kpp = 301
  INTEGER, PARAMETER :: gocartradm2 = 303

  INTEGER, PARAMETER :: mozart_kpp = 111
  INTEGER, PARAMETER :: mozart_mosaic_4bin_aq_kpp = 202
  INTEGER, PARAMETER :: mozart_mosaic_4bin_kpp = 201
  INTEGER, PARAMETER :: mozcart_kpp = 112

  INTEGER, PARAMETER :: racmsorg_aq = 12

  INTEGER, PARAMETER :: radm2 = 1
  INTEGER, PARAMETER :: radm2sorg = 2
  INTEGER, PARAMETER :: radm2sorg_aq = 11
  INTEGER, PARAMETER :: radm2sorg_aqaqm = 41
  INTEGER, PARAMETER :: racmsoavbs_kpp = 108

  ! -- nbegin is the start address (-1) of the first aqm variable in tr3d
  integer :: nbegin

  integer :: year_track_data = 0

  type(aqm_config_type), pointer :: aqm_config => null()

  public 

contains

  subroutine aqm_tracers_set(config, rc)
    type(aqm_config_type), pointer     :: config
!   type(aqm_config_type), intent(in)  :: config
    integer, optional,      intent(out) :: rc

    ! -- begin
    if (present(rc)) rc = AQM_RC_SUCCESS

    aqm_config    => config

!   num_aqm       = config % num_aqm
!   num_moist      = config % num_moist

    p_atm_shum     = config % species % p_atm_shum
    p_atm_cldq     = config % species % p_atm_cldq
    p_atm_o3mr     = config % species % p_atm_o3mr

    p_ac0          = config % species % p_ac0
    p_aco3         = config % species % p_aco3
    p_ald          = config % species % p_ald
    p_antha        = config % species % p_antha
    p_api          = config % species % p_api
    p_asoa1i       = config % species % p_asoa1i
    p_asoa1j       = config % species % p_asoa1j
    p_asoa2i       = config % species % p_asoa2i
    p_asoa2j       = config % species % p_asoa2j
    p_asoa3i       = config % species % p_asoa3i
    p_asoa3j       = config % species % p_asoa3j
    p_asoa4i       = config % species % p_asoa4i
    p_asoa4j       = config % species % p_asoa4j
    p_asympar106   = config % species % p_asympar106
    p_asympar3     = config % species % p_asympar3
    p_asympar55    = config % species % p_asympar55
    p_bc1          = config % species % p_bc1
    p_bc2          = config % species % p_bc2
    p_bscof106     = config % species % p_bscof106
    p_bscof3       = config % species % p_bscof3
    p_bscof55      = config % species % p_bscof55
    p_bsoa1i       = config % species % p_bsoa1i
    p_bsoa1j       = config % species % p_bsoa1j
    p_bsoa2i       = config % species % p_bsoa2i
    p_bsoa2j       = config % species % p_bsoa2j
    p_bsoa3i       = config % species % p_bsoa3i
    p_bsoa3j       = config % species % p_bsoa3j
    p_bsoa4i       = config % species % p_bsoa4i
    p_bsoa4j       = config % species % p_bsoa4j
    p_ch4          = config % species % p_ch4
    p_clai         = config % species % p_clai
    p_claj         = config % species % p_claj
    p_co           = config % species % p_co
    p_co2          = config % species % p_co2
    p_corn         = config % species % p_corn
    p_csl          = config % species % p_csl
    p_cvasoa1      = config % species % p_cvasoa1
    p_cvasoa2      = config % species % p_cvasoa2
    p_cvasoa3      = config % species % p_cvasoa3
    p_cvasoa4      = config % species % p_cvasoa4
    p_cvbsoa1      = config % species % p_cvbsoa1
    p_cvbsoa2      = config % species % p_cvbsoa2
    p_cvbsoa3      = config % species % p_cvbsoa3
    p_cvbsoa4      = config % species % p_cvbsoa4
    p_dcb          = config % species % p_dcb
    p_dien         = config % species % p_dien
    p_dms          = config % species % p_dms
    p_dust_1       = config % species % p_dust_1
    p_dust_2       = config % species % p_dust_2
    p_dust_3       = config % species % p_dust_3
    p_dust_4       = config % species % p_dust_4
    p_dust_5       = config % species % p_dust_5
    p_e_ald        = config % species % p_e_ald
    p_e_bc         = config % species % p_e_bc
    p_e_co         = config % species % p_e_co
    p_e_csl        = config % species % p_e_csl
    p_e_dms        = config % species % p_e_dms
    p_e_eth        = config % species % p_e_eth
    p_e_hc3        = config % species % p_e_hc3
    p_e_hc5        = config % species % p_e_hc5
    p_e_hc8        = config % species % p_e_hc8
    p_e_hcho       = config % species % p_e_hcho
    p_e_iso        = config % species % p_e_iso
    p_e_ket        = config % species % p_e_ket
    p_e_nh3        = config % species % p_e_nh3
    p_e_no         = config % species % p_e_no
    p_e_no2        = config % species % p_e_no2
    p_e_oc         = config % species % p_e_oc
    p_e_oli        = config % species % p_e_oli
    p_e_olt        = config % species % p_e_olt
    p_e_ora2       = config % species % p_e_ora2
    p_e_pm_10      = config % species % p_e_pm_10
    p_e_pm_25      = config % species % p_e_pm_25
    p_e_so2        = config % species % p_e_so2
    p_e_sulf       = config % species % p_e_sulf
    p_e_tol        = config % species % p_e_tol
    p_e_tr1        = config % species % p_e_tr1
    p_e_tr2        = config % species % p_e_tr2
    p_e_tr3        = config % species % p_e_tr3
    p_e_tr4        = config % species % p_e_tr4
    p_e_tr5        = config % species % p_e_tr5
    p_e_vash1      = config % species % p_e_vash1
    p_e_vash10     = config % species % p_e_vash10
    p_e_vash2      = config % species % p_e_vash2
    p_e_vash3      = config % species % p_e_vash3
    p_e_vash4      = config % species % p_e_vash4
    p_e_vash5      = config % species % p_e_vash5
    p_e_vash6      = config % species % p_e_vash6
    p_e_vash7      = config % species % p_e_vash7
    p_e_vash8      = config % species % p_e_vash8
    p_e_vash9      = config % species % p_e_vash9
    p_e_xyl        = config % species % p_e_xyl
    p_ebu_ald      = config % species % p_ebu_ald
    p_ebu_bc       = config % species % p_ebu_bc
    p_ebu_co       = config % species % p_ebu_co
    p_ebu_csl      = config % species % p_ebu_csl
    p_ebu_dms      = config % species % p_ebu_dms
    p_ebu_eth      = config % species % p_ebu_eth
    p_ebu_hc3      = config % species % p_ebu_hc3
    p_ebu_hc5      = config % species % p_ebu_hc5
    p_ebu_hc8      = config % species % p_ebu_hc8
    p_ebu_hcho     = config % species % p_ebu_hcho
    p_ebu_in_ald   = config % species % p_ebu_in_ald
    p_ebu_in_bc    = config % species % p_ebu_in_bc
    p_ebu_in_co    = config % species % p_ebu_in_co
    p_ebu_in_csl   = config % species % p_ebu_in_csl
    p_ebu_in_dms   = config % species % p_ebu_in_dms
    p_ebu_in_eth   = config % species % p_ebu_in_eth
    p_ebu_in_hc3   = config % species % p_ebu_in_hc3
    p_ebu_in_hc5   = config % species % p_ebu_in_hc5
    p_ebu_in_hc8   = config % species % p_ebu_in_hc8
    p_ebu_in_hcho  = config % species % p_ebu_in_hcho
    p_ebu_in_iso   = config % species % p_ebu_in_iso
    p_ebu_in_ket   = config % species % p_ebu_in_ket
    p_ebu_in_nh3   = config % species % p_ebu_in_nh3
    p_ebu_in_no    = config % species % p_ebu_in_no
    p_ebu_in_no2   = config % species % p_ebu_in_no2
    p_ebu_in_oc    = config % species % p_ebu_in_oc
    p_ebu_in_oli   = config % species % p_ebu_in_oli
    p_ebu_in_olt   = config % species % p_ebu_in_olt
    p_ebu_in_ora2  = config % species % p_ebu_in_ora2
    p_ebu_in_pm10  = config % species % p_ebu_in_pm10
    p_ebu_in_pm25  = config % species % p_ebu_in_pm25
    p_ebu_in_so2   = config % species % p_ebu_in_so2
    p_ebu_in_sulf  = config % species % p_ebu_in_sulf
    p_ebu_in_tol   = config % species % p_ebu_in_tol
    p_ebu_in_xyl   = config % species % p_ebu_in_xyl
    p_ebu_iso      = config % species % p_ebu_iso
    p_ebu_ket      = config % species % p_ebu_ket
    p_ebu_nh3      = config % species % p_ebu_nh3
    p_ebu_no       = config % species % p_ebu_no
    p_ebu_no2      = config % species % p_ebu_no2
    p_ebu_oc       = config % species % p_ebu_oc
    p_ebu_oli      = config % species % p_ebu_oli
    p_ebu_olt      = config % species % p_ebu_olt
    p_ebu_ora2     = config % species % p_ebu_ora2
    p_ebu_pm10     = config % species % p_ebu_pm10
    p_ebu_pm25     = config % species % p_ebu_pm25
    p_ebu_so2      = config % species % p_ebu_so2
    p_ebu_sulf     = config % species % p_ebu_sulf
    p_ebu_tol      = config % species % p_ebu_tol
    p_ebu_xyl      = config % species % p_ebu_xyl
    p_eci          = config % species % p_eci
    p_ecj          = config % species % p_ecj
    p_edust1       = config % species % p_edust1
    p_edust2       = config % species % p_edust2
    p_edust3       = config % species % p_edust3
    p_edust4       = config % species % p_edust4
    p_edust5       = config % species % p_edust5
    p_eseas1       = config % species % p_eseas1
    p_eseas2       = config % species % p_eseas2
    p_eseas3       = config % species % p_eseas3
    p_eseas4       = config % species % p_eseas4
    p_ete          = config % species % p_ete
    p_eth          = config % species % p_eth
    p_extcof106    = config % species % p_extcof106
    p_extcof3      = config % species % p_extcof3
    p_extcof3_5    = config % species % p_extcof3_5
    p_extcof55     = config % species % p_extcof55
    p_extcof8_12   = config % species % p_extcof8_12
    p_gly          = config % species % p_gly
    p_h2o2         = config % species % p_h2o2
    p_hace         = config % species % p_hace
    p_hc3          = config % species % p_hc3
    p_hc5          = config % species % p_hc5
    p_hc8          = config % species % p_hc8
    p_hcho         = config % species % p_hcho
    p_hket         = config % species % p_hket
    p_hno3         = config % species % p_hno3
    p_hno4         = config % species % p_hno4
    p_ho           = config % species % p_ho
    p_ho2          = config % species % p_ho2
    p_hono         = config % species % p_hono
    p_ishp         = config % species % p_ishp
    p_iso          = config % species % p_iso
    p_ison         = config % species % p_ison
    p_ket          = config % species % p_ket
    p_lim          = config % species % p_lim
    p_macr         = config % species % p_macr
    p_mahp         = config % species % p_mahp
    p_mbo          = config % species % p_mbo
    p_mgly         = config % species % p_mgly
    p_mpan         = config % species % p_mpan
    p_msa          = config % species % p_msa
    p_n2o5         = config % species % p_n2o5
    p_naai         = config % species % p_naai
    p_naaj         = config % species % p_naaj
    p_nald         = config % species % p_nald
    p_nh3          = config % species % p_nh3
    p_nh4ai        = config % species % p_nh4ai
    p_nh4aj        = config % species % p_nh4aj
    p_no           = config % species % p_no
    p_no2          = config % species % p_no2
    p_no3          = config % species % p_no3
    p_no3ai        = config % species % p_no3ai
    p_no3aj        = config % species % p_no3aj
    p_nu0          = config % species % p_nu0
    p_o3           = config % species % p_o3
    p_oc1          = config % species % p_oc1
    p_oc2          = config % species % p_oc2
    p_oli          = config % species % p_oli
    p_olt          = config % species % p_olt
    p_onit         = config % species % p_onit
    p_op1          = config % species % p_op1
    p_op2          = config % species % p_op2
    p_ora1         = config % species % p_ora1
    p_ora2         = config % species % p_ora2
    p_orgpai       = config % species % p_orgpai
    p_orgpaj       = config % species % p_orgpaj
    p_p10          = config % species % p_p10
    p_p25          = config % species % p_p25
    p_p25i         = config % species % p_p25i
    p_p25j         = config % species % p_p25j
    p_paa          = config % species % p_paa
    p_pan          = config % species % p_pan
    p_qc           = config % species % p_qc
    p_qi           = config % species % p_qi
    p_qv           = config % species % p_qv
    p_seas         = config % species % p_seas
    p_seas_1       = config % species % p_seas_1
    p_seas_2       = config % species % p_seas_2
    p_seas_3       = config % species % p_seas_3
    p_seas_4       = config % species % p_seas_4
    p_sesq         = config % species % p_sesq
    p_so2          = config % species % p_so2
    p_so4ai        = config % species % p_so4ai
    p_so4aj        = config % species % p_so4aj
    p_soila        = config % species % p_soila
    p_sulf         = config % species % p_sulf
    p_tol          = config % species % p_tol
    p_tpan         = config % species % p_tpan
    p_tr1          = config % species % p_tr1
    p_tr2          = config % species % p_tr2
    p_tr3          = config % species % p_tr3
    p_tr4          = config % species % p_tr4
    p_tr5          = config % species % p_tr5
    p_udd          = config % species % p_udd
    p_vash_1       = config % species % p_vash_1
    p_vash_10      = config % species % p_vash_10
    p_vash_2       = config % species % p_vash_2
    p_vash_3       = config % species % p_vash_3
    p_vash_4       = config % species % p_vash_4
    p_vash_5       = config % species % p_vash_5
    p_vash_6       = config % species % p_vash_6
    p_vash_7       = config % species % p_vash_7
    p_vash_8       = config % species % p_vash_8
    p_vash_9       = config % species % p_vash_9
    p_xyl          = config % species % p_xyl

  end subroutine aqm_tracers_set

end module aqm_tracers_mod
